### ISSUE TITLE
尝试兼容 puppeteer

### ISSUE THREAD

**Issue by xudafeng** [macacajs/torchjs#19]

**Comment by leungwensen** [comment]
看了一下，它和nightmare有点类似，主要是提供自动化脚本能力的，用来做UI交互测试比较多。如果要兼容这一类的工具，electron原本的node injection之类的特性就做不了了，这就意味着没法在测试用例里使用原生node模块、预编译某些测试用例或者源代码。基于puppeteer或许也能做目前torchjs的功能，但会很难的。

**Comment by xudafeng** [comment]
是的，看puppeteer的发展方向吧，如果面向研发者端可能会取代掉electron。issue先关了
