### ISSUE TITLE
HTTP 模式下 `run.js` require 不到

### ISSUE THREAD

**Issue by meowtec** [macacajs/torchjs#31]
https://github.com/macacajs/torchjs/commit/c05b9bfb27f334f316538007fe70107de42c54d1#diff-168726dbe96b3ce427e7fedce31bb0bc

不知道这里为什么把 run.js 的绝对路径改成了相对路径

**Comment by leungwensen** [comment]
改为相对路径是因为在 windows 下绝对路径塞到 require 函数里是请求不到的，因为这个路径和 npm 解释模块路径完全不兼容。你说的 HTTP 模式下请求不到，能不能给个具体的复现的 case？（可以给我个可以重现的项目链接之类的吗）

@meowtec

**Comment by meowtec** [comment]
不需要重现的 case，你随便找个空目录运行

```
npx  torch --compile --renderer --http --recursive ./ --interactive
```

就能看到报错。

@leungwensen

**Comment by leungwensen** [comment]
torchjs@2.0.2  @meowtec

**Comment by meowtec** [comment]
@leungwensen 我在 windows 10 下试过 OK 的啊，不兼容的情况是怎么样出现的？
